# Ручные правки к автоматически собранному словарю.
#
# Автоматика ошибается примерно в 5% случаев, и почти всегда одинаково:
# у прилагательного или глагольной формы есть редкий омоним-существительное,
# и Викисловарь отдаёт именно его («lekker» → «протечка» вместо «вкусный»).
# Часть таких случаев ловится правилом (см. NOMINALIZATION_RE в build.py),
# остальное перечислено здесь после ручного просмотра уровня A1.

# Слова, которые вообще не нужны в карточках:
# субстантивации, глагольные формы, случайные омонимы.
BLACKLIST = {
    'goed', 'hou', 'wacht', 'goede', 'zelf', 'thuis', 'praat', 'mis', 'lekker',
    'wees', 'dicht', 'normaal', 'slechte', 'zwarte', 'frank', 'leek', 'waard',
    'dom', 'derde', 'vreemde', 'jong', 'gezet', 'geleerd', 'steek', 'kwijt',
    'sla', 'dode', 'spijt', 'dank', 'haat', 'hoop', 'orde', 'kost', 'val',
    'raad', 'maat', 'rijk', 'slag', 'stel', 'deel', 'eind', 'begin', 'bereid',
    'betrokken', 'afgelopen', 'bekend', 'getrouwd', 'geboren', 'levend',
    'gevecht', 'overleven', 'bestaan', 'gebeuren', 'eten', 'drinken', 'donker',
    'midden', 'net', 'keer', 'gang', 'bel', 'zoek', 'druk', 'schat',
    # Форми множини, які Вікісловник тлумачить як окреме рідкісне слово:
    # dingen «клопотати» замість «речі», dagen «світати» замість «дні».
    'dingen', 'dagen', 'ogen', 'weken', 'benen', 'sporen', 'gevallen',
    'gek', 'raak', 'los', 'neer', 'erop', 'vandaan', 'zover', 'waarvoor',
    'kwalijk', 'stellen', 'delen', 'plannen', 'boeken', 'getuigen', 'dromen',
    'doden', 'ergens', 'vast', 'zin',
    # Те саме в діапазоні A2: множина або дієприкметник, який Вікісловник
    # тлумачить як окреме слово (schepen «олдермен» замість «кораблі»).
    'schoot', 'moorden', 'engels', 'harde', 'war', 'gaande', 'bleek',
    'huizen', 'schepen', 'brak', 'bomen', 'groene', 'rijke', 'bergen',
    'vandoor', 'ervandoor', 'papieren', 'verhalen', 'kaarten', 'neuken',
    'high', 'klote', 'besloten', 'genoemd', 'aangedaan', 'vernietigd',
    'super', 'sexy', 'west', 'de', 'wc',
    'stenen', 'vierde', 'terugkomt', 'ex', 'heilige', 'gevangene',
    # Діапазон B1
    'omwille', 'binnenuit', 'blikken', 'hakken', 'pijpen', 'munten',
    'achterste', 'jarig',
    # Форми множини, яким Вікісловник дав рідкісне дієслівне значення:
    # «stoelen» не «ґрунтуватися», а «стільці»; «doelen» — «цілі», не «цілитися».
    'katten', 'glazen', 'boten', 'luizen', 'stoelen', 'blanken', 'chinezen',
    'stalen', 'metalen', 'bladeren', 'zinnen', 'spoken', 'doelen', 'banen',
    'poten', 'lijnen', 'koppen', 'blokken', 'flessen', 'boeien', 'scholen',
    'golven', 'treden', 'poppen', 'oorlogen', 'veren', 'billen', 'poorten',
    'talen', 'kisten', 'malen', 'wateren', 'stammen', 'strepen', 'vlekken',
    'stoffen', 'rotten', 'paren', 'smaken', 'wenen',
    # Англіцизми та мета-глоси, що просочилися
    'go', 'hot', 'close', 'down', 'hoever', 'maling', 'tekeer', 'quitte',
    'schrap', 'loos', 'piep', 'tering', 'poen', 'internationaal',
    'aanstaande', 'gedeeld', 'ingezet', 'gemeld', 'zoet', 'droge', 'stille',
    'smelt', 'uiten', 'raven',
    # Вульгаризми — не для навчальних карток
    'kloten', 'pissen', 'geil',
    # B2/C1: вульгаризми, сленг і хибні тлумачення.
    # Перевірку «дієслово збігається з формою множини» тут застосовувати
    # автоматично не можна — більшість таких слів (fluiten, vouwen, niezen)
    # цілком нормальні дієслова. Тому список ручний.
    'vuisten', 'scheten', 'poepen', 'vossen', 'geiten', 'buizen', 'slijmen',
    'jatten', 'dollen', 'sollen', 'mokken', 'boffen', 'zwijnen', 'klooien',
    'pitten', 'moppen', 'krukken', 'klieren', 'meppen', 'dokken', 'wippen',
    'fabrieken', 'temperaturen', 'rijen', 'azen', 'palen', 'peren',
    'schrammen', 'blaren', 'groeven', 'stallen', 'bussen', 'potten',
    'tuinen', 'mollen', 'stokken', 'proppen', 'trollen', 'brokken',
    'neuzen', 'gieren', 'staven', 'luiden', 'gronden', 'ronden', 'gissen',
    'her', 'zoal', 'koele', 'voorbije', 'franco', 'mini', 'wars', 'doods',
}

# Точечные исправления значения: слово → правильный английский перевод.
# Артикль (если нужен) указывается вместе со словом в ключе 'w'.
FIXES = {
    'stom':          {'t': 'stupid, dumb'},
    'vroeger':       {'t': 'formerly, in the past'},
    'uiteindelijk':  {'t': 'finally, in the end'},
    'schelen':       {'t': 'to matter, to make a difference'},
    'brand':         {'t': 'fire, blaze'},
    'bank':          {'t': 'sofa, couch; bank'},
    'gek':           {'t': 'crazy, mad'},
    'zin':           {'t': 'sentence; sense; desire'},
    'stuk':          {'t': 'piece, part'},
    'recht':         {'t': 'right, law'},
    'geval':         {'t': 'case, instance'},
    'been':          {'t': 'leg; bone'},
    'lijk':          {'t': 'corpse, dead body'},
    'ongeluk':       {'t': 'accident; misfortune'},
    'rekening':      {'t': 'bill, invoice; account'},
    'gezicht':       {'t': 'face'},
    'baan':          {'t': 'job; lane, track'},
    'blij':          {'t': 'glad, happy'},
    'heer':          {'t': 'gentleman, sir; lord'},
    'regel':         {'t': 'rule; line of text'},
    'pak':           {'t': 'suit; pack, packet'},
    'kop':           {'t': 'head (of an animal); cup'},
    'zaak':          {'t': 'case, matter; business'},
    'band':          {'t': 'tyre; tape; bond'},
    'controle':      {'t': 'check, inspection; control'},
    'hoeven':        {'t': 'to need to, to have to'},
    'lijst':         {'t': 'list; frame'},
    'spoor':         {'t': 'track, trail; railway'},
    'monster':       {'t': 'monster; sample'},
    'stuur':         {'t': 'steering wheel; handlebars'},
    'macht':         {'t': 'power, might'},
    'moeite':        {'t': 'effort, trouble'},
    'leraar':        {'t': 'teacher'},
    'code':          {'t': 'code'},
    'akkoord':       {'t': 'agreement; chord'},
    'stappen':       {'t': 'to step, to walk'},
    'heus':          {'t': 'really, truly'},
    'wetenschap':    {'t': 'science'},
    'vlak':          {'t': 'flat surface, plane'},
    'post':          {'t': 'mail, post; post, position'},
    'bek':           {'t': 'beak, snout; mouth'},
    'streek':        {'t': 'region, area'},
    'pers':          {'t': 'press (media); press (machine)'},
    'gaaf':          {'t': 'cool, great; intact'},
    'boel':          {'t': 'a lot, a bunch; stuff'},
    'blik':          {'t': 'look, glance; tin, can'},
    'voorkomen':     {'t': 'appearance; to occur; to prevent'},
    'ontzettend':    {'t': 'terribly, extremely'},
    'kerstmis':      {'t': 'Christmas'},
    'champagne':     {'t': 'champagne'},
    'wijze':         {'t': 'way, manner'},
    'bak':           {'t': 'container, bin, tray'},
    'lijden':        {'t': 'suffering; to suffer'},
    'top':           {'t': 'top, summit'},
    'rol':           {'t': 'role; roll'},
    'trap':          {'t': 'stairs; kick'},
    'leer':          {'t': 'leather; doctrine'},
    'stof':          {'t': 'dust; fabric; substance'},
    'gedragen':      {'t': 'to behave (oneself)'},
    'aanvallen':     {'t': 'to attack'},
    'passen':        {'t': 'to fit; to try on'},
    'keren':         {'t': 'to turn'},
    'voeren':        {'t': 'to carry out; to feed'},
    'zakken':        {'t': 'to sink, to drop; to fail (an exam)'},
    'lol':           {'t': 'fun'},
    'kussen':        {'t': 'pillow; to kiss'},
    # Значення, які Вікісловник подає хибно або надто вузько.
    # Правимо саме тут: FIXES міняють лише текст, а не склад словника,
    # тому українські переклади лишаються прив'язаними до тих самих слів.
    'spion':         {'t': 'spy'},
    'pop':           {'t': 'doll; pop music'},
    'aanslag':       {'t': 'attack, assassination attempt'},
    'leest':         {'t': "shoemaker's last"},
    'vaste':         {'t': 'fixed, permanent one'},
    'vuren':         {'t': 'spruce wood; to fire'},
    'ramen':         {'t': 'windows; to estimate'},
    'kanten':        {'t': 'sides; lace-made'},
    'botten':        {'t': 'bones; to collide'},
    'middelen':      {'t': 'means, resources'},
    'wetten':        {'t': 'laws; to whet'},
    'lessen':        {'t': 'lessons; to quench'},
    'tranen':        {'t': 'tears; to water (of eyes)'},
    'tel':           {'t': 'count, counting'},
    'illegaal':      {'t': 'illegal; illegal immigrant'},
    'zieke':         {'t': 'sick person, patient'},
    'oudste':        {'t': 'eldest, oldest'},
    'bekende':       {'t': 'acquaintance'},
    'casino':        {'t': 'casino'},
    'on':            {'t': 'un-, non- (prefix)'},
    'golf':          {'t': 'wave; golf'},
    'centrale':      {'t': 'power plant; central office'},
    'wild':          {'t': 'game (animals); wild'},
    'stand':         {'t': 'position; score; stall'},
    # B2/C1
    'poster':        {'t': 'poster'},
    'pasen':         {'t': 'Easter'},
    'flippen':       {'t': 'to freak out, to flip'},
    'hip':           {'t': 'hip, trendy'},
    'hop':           {'t': 'hops; hoopoe'},
    'vatten':        {'t': 'to grasp, to catch'},
    'schaken':       {'t': 'to play chess'},
    'plee':          {'t': 'loo, toilet'},
    'begeven':       {'t': 'to give way, to break down'},
    'overgaan':      {'t': 'to turn into; to ring (of a phone)'},
    'klaren':        {'t': 'to manage, to get done'},
    'streven':       {'t': 'to strive, to aim for'},
    'achten':        {'t': 'to consider, to esteem'},
    'gezamenlijk':   {'t': 'joint, together'},
    'kapitaal':      {'t': 'capital, fortune'},
}
